### ISSUE TITLE
bazel build error

### ISSUE THREAD

**Issue by kitaharasetusna** [DAIRLab/dairlib#354]
Hi, I ran through you guidance and when I tried to build using bazel build ..., the error is raised:
'   Traceback (most recent call last):
	File "/home/bear/.cache/bazel/_bazel_bear/79f7bd47455108254ab9cc8408e70aff/external/drake/tools/workspace/python/repository.bzl", line 128, column 37, in _impl
		py_info = repository_python_info(
	File "/home/bear/.cache/bazel/_bazel_bear/79f7bd47455108254ab9cc8408e70aff/external/drake/tools/workspace/python/repository.bzl", line 62, column 13, in repository_python_info
		fail(os_result.error)
Error in fail: could not determine Linux distribution: unsupported 'Ubuntu' release '18.04'
'
My settings are:
ubuntu 18.04
ros melodic

**Comment by mposa** [comment]
Ah! It looks like we need to update the README. To stay up to date with Drake, we've discontinued support for Ubuntu 18.04, so you'd have to upgrade to 20.04 or 22.04.
